### ISSUE TITLE
功能描述

### ISSUE THREAD

**Issue by XL370** [Hanan-Lu/DIY-Link-V9#1]
支持SPI的采样和仿真模拟吗？

**Comment by Hanan-Lu** [comment]
不支持，J-Link V9版本仅支持使用J-Flash SPI来烧录SPI Flash(例如W25Qxx), 采样和仿真模拟建议使用逻辑分析仪及数字信号发生器(例如稚晖君的[UltraLink](https://www.bilibili.com/video/BV1o24y187Gc/?spm_id_from=333.999.0.0&vd_source=e817f6f8f3cb4b81a3ef86c72f5b0c7a))
